server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.25.129:3306/kafka
    username: root
    password: root
    driverClassname: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: 192.168.25.129:9092
    topic: retry-topic

    # producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    # consumer
    consumer:
      group-id: kafka-retry
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"